name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Set up Java for backend
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Install Maven Wrapper
        working-directory: backend
        run: mvn -N io.takari:maven:wrapper

      - name: Build backend
        working-directory: backend
        run: ./mvnw clean install

      - name: Run frontend tests
        working-directory: frontend
        run: npm test

      - name: Run frontend lint
        working-directory: frontend
        run: npm run lint

      - name: Run backend tests
        working-directory: backend
        run: ./mvnw test
